BackEnd/config/routes.rb
PostsApp::Application.routes.draw do
  resources :users
  resources :tags
  resources :posts
  resource :session
end

BackEnd/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :body, :user_id, presence: true
  has_many :tags
  belongs_to :user
end

BackEnd/app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
end

BackEnd/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token
  attr_reader :password
  has_many :posts
  
  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
    
end

BackEnd/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end
  
  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_login!
    redirect_to new_session_url unless logged_in?
  end
end

BackEnd/app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :require_login!
   
  def index
    @posts = current_user.posts
  end

  def show
    @post = current_user.posts.find(params[:id])
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      render :edit
    end
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      render :new
    end
  end

  def new
    @post = Post.new
  end
  
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

BackEnd/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login!(@user)
      redirect_to posts_url
    else
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

BackEnd/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_login!
  def create
    @tag = Tag.new(tag_params)
    @tag.save
    redirect_to post_url(@tag.post)
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to post_url(@tag.post)
  end
  
  private
  def tag_params
    params.require(:tag).permit(:name, :post_id)
  end
end

BackEnd/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to posts_url
    else
      render :new
    end
  end

  def new
    @user = User.new
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

BackEnd/app/helpers/application_helper.rb
module ApplicationHelper
end

BackEnd/app/helpers/posts_helper.rb
module PostsHelper
end

BackEnd/app/helpers/sessions_helper.rb
module SessionsHelper
end

BackEnd/app/helpers/tag_helper.rb
module TagHelper
end

BackEnd/app/helpers/tags_helper.rb
module TagsHelper
end

BackEnd/app/helpers/users_helper.rb
module UsersHelper
end

BackEnd/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assessment04</title>
</head>
<body>
	
	<% if logged_in? %>
	<%= current_user.username %>
	<%= button_to "Sign Out", session_url, method: :delete%>
	<% else %>
	<%= link_to "Sign In", new_session_url %>
	<%= link_to "Sign Up", new_user_url %>
	<% end %>

<%= yield %>

</body>
</html>

BackEnd/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

BackEnd/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action="<%= post_url(@post) %>" method="POST">
	<input type="hidden" name="_method" value="PATCH">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	
	<label for="title">Title</label>
	<input type="text" id="title" name="post[title]" value="<%= @post.title %>">
	
	<label for="body">Body</label>
	<input type="text" id="body" name="post[body]" value="<%= @post.body %>">
	
	<input type="submit" value="Update Post">
</form>

BackEnd/app/views/posts/index.html.erb
<% @posts.each do |post| %>
<p><%= link_to post.title, post_url(post) %></p>
<% end %>

BackEnd/app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%= posts_url %>" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	
	<label for="title">Title</label>
	<input type="text" id="title" name="post[title]" value="<%= @post.title %>">
	
	<label for="body">Body</label>
	<input type="text" id="body" name="post[body]" value="<%= @post.body %>">
	
	<input type="submit" value="Create New Post">
</form>

BackEnd/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h1><%= @post.body %></h1>
<%= link_to "Edit Post", edit_post_url %>

<h1>Add Tag</h1>

<form action="<%= tags_url %>" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	
	<label for="tagname">Tag Name</label>
	<input type="text" id="tagname" name="tag[name]">
	
	<input type="hidden" name="tag[post_id]" value="<%= @post.id %>">
	
	<input type="submit" value="Add Tag">
</form>

<% @post.tags.each do |tag| %>
<p><%= tag.name %><%= button_to "Remove Tag", tag_url(tag), method: :delete %></p>
<% end %>

BackEnd/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

BackEnd/app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

BackEnd/app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

BackEnd/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

BackEnd/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	
	<label for="username">Username</label>
	<input type="text" id="username" name="user[username]" value="<%= @user.username %>">
	
	<label for="password">Password</label>
	<input type="password" id="password" name="user[password]">
	
	<input type="submit" value="Sign Up">
</form>